# Generated by Django 2.1.3 on 2018-12-16 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Nif', models.CharField(max_length=50)),
                ('Country', models.CharField(choices=[('SP', 'Spain'), ('GR', 'Germany'), ('PR', 'Portugal'), ('IT', 'Italy')], max_length=2)),
                ('City', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=60)),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaleOrdersExample.Client')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Qty', models.IntegerField(default=0)),
                ('IdProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaleOrdersExample.Product')),
                ('IdSale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaleOrdersExample.SaleOrder')),
            ],
        ),
    ]
